"""empty message

Revision ID: 7312e630a336
Revises: b18fcc3dc19e
Create Date: 2019-11-30 23:50:30.424998

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7312e630a336'
down_revision = 'b18fcc3dc19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('actions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actions',
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('updated', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), nullable=True),
    sa.Column('task_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('updated', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('name', sa.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
