"""empty message

Revision ID: 7b60f1c51838
Revises: 967c4474d04b
Create Date: 2019-12-01 16:14:40.741037

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '7b60f1c51838'
down_revision = '967c4474d04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actions', 'name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('tasks', 'name',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.alter_column('actions', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###
