"""empty message

Revision ID: 967c4474d04b
Revises: 90d0f2a0337a
Create Date: 2019-12-01 14:34:24.055324

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '967c4474d04b'
down_revision = '90d0f2a0337a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_name_task', 'actions', ['name', 'task_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_name_task', 'actions', type_='unique')
    # ### end Alembic commands ###
